name: circular_page_view
description: A Flutter package for Android, iOS & Web which helps creating animated circular page views with customizable options.
version: 0.0.2
homepage: https://github.com/mayurnile/circular_page_view.git

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

